/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/chiesa.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

function Chiesa(props) {
  const { nodes, materials } = useGLTF("/chiesa.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Navata_Centrale.geometry}>
        <meshStandardMaterial color="#a08060" />
      </mesh>
      <mesh geometry={nodes.Ala_Sinistra.geometry} scale={[1, 1.15, 1]}>
        <meshStandardMaterial color="#a08060" />
      </mesh>
      <mesh geometry={nodes.Ala_Destra.geometry} scale={[1, 1.15, 1]}>
        <meshStandardMaterial color="#a08060" />
      </mesh>
      <mesh geometry={nodes.Campanile.geometry} position={[0, 0, 5]}>
        <meshStandardMaterial color="#a08060" />
      </mesh>
      <mesh
        geometry={nodes.Cone.geometry}
        position={[-3, 18.5, 0]}
        rotation={[0, Math.PI / 4, 0]}
      >
        <meshStandardMaterial color="#a08060" />
      </mesh>
      <mesh
        geometry={nodes.Campanile001.geometry}
        position={[1.4, 9, -2.5]}
        scale={[0.5, 0.1, 0.5]}
      >
        <meshStandardMaterial color="#a08060" />
      </mesh>
      <mesh
        geometry={nodes.Navata_Centrale001.geometry}
        position={[-0.122, 0, 4.2]}
        scale={[1, 0.8, 0.88]}
      >
        <meshStandardMaterial color="#a08060" />
      </mesh>
      <mesh
        geometry={nodes.Ala_Destra001.geometry}
        position={[-0.1, 0, 7.7]}
        scale={[1.03, 0.91, 0.3]}
      >
        <meshStandardMaterial color="#a08060" />
      </mesh>
      <mesh
        geometry={nodes.Ala_Destra002.geometry}
        position={[0, -0.147, 7.7]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[1, 0.94, 0.3]}
      >
        <meshStandardMaterial color="#a08060" />
      </mesh>
      <mesh
        geometry={nodes.Campanile002.geometry}
        position={[0.08, 10.7, -4.7]}
        scale={0.05}
      >
        <meshStandardMaterial color="#a08060" />
      </mesh>
      <mesh
        geometry={nodes.Campanile003.geometry}
        position={[-0.5, 11, -4.647]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.05}
      >
        <meshStandardMaterial color="#a08060" />
      </mesh>
      <mesh
        geometry={nodes.Cone001.geometry}
        position={[-0.129, 7.15, 7.6]}
        rotation={[0, Math.PI / 4, 0]}
        scale={[2.6, 0.5, 2.6]}
      >
        <meshStandardMaterial color="#a08060" />
      </mesh>
      <mesh
        geometry={nodes.Cube.geometry}
        position={[0, 8.769, 0]}
        scale={[2.2, 1, 6]}
      >
        <meshStandardMaterial color="#a08060" />
      </mesh>
      <mesh
        geometry={nodes.Cube001.geometry}
        position={[1.9, 8.2, -6]}
        rotation={[0, 0, -0.698]}
        scale={[2.85, 0.1, 0.1]}
      >
        <meshStandardMaterial color="#c8b89a" />
      </mesh>
      <mesh
        geometry={nodes.Cube002.geometry}
        position={[0, 6.3, -6]}
        scale={[4, 0.1, 0.1]}
      >
        <meshStandardMaterial color="#c8b89a" />
      </mesh>
      <mesh
        geometry={nodes.Cube003.geometry}
        position={[-2, 8.2, -6]}
        rotation={[0, 0, 0.768]}
        scale={[2.7, 0.1, 0.1]}
      >
        <meshStandardMaterial color="#c8b89a" />
      </mesh>
      <mesh
        geometry={nodes.Cube004.geometry}
        position={[-1.069, 1.5, -6]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[1.6, 0.1, 0.1]}
      >
        <meshStandardMaterial color="#c8b89a" />
      </mesh>
      <mesh
        geometry={nodes.Cube005.geometry}
        position={[1.033, 1.5, -6]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[1.6, 0.1, 0.1]}
      >
        <meshStandardMaterial color="#c8b89a" />
      </mesh>
      <mesh
        geometry={nodes.Cube006.geometry}
        position={[-2.5, 0.2, 2]}
        scale={[0.5, 0.4, 0.5]}
      >
        <meshStandardMaterial color="#a08060" />
      </mesh>
      <mesh geometry={nodes.Cylinder.geometry} position={[-2.5, 2.5, 2]}>
        <meshStandardMaterial color="#a08060" />
      </mesh>
      <mesh geometry={nodes.Cone002.geometry} position={[-2.5, 5, 2]}>
        <meshStandardMaterial color="#a08060" />
      </mesh>
      <mesh
        geometry={nodes.Cube007.geometry}
        position={[2.5, 0.2, 2]}
        scale={[0.5, 0.4, 0.5]}
      >
        <meshStandardMaterial color="#a08060" />
      </mesh>
      <mesh geometry={nodes.Cylinder001.geometry} position={[2.5, 2.5, 2]}>
        <meshStandardMaterial color="#a08060" />
      </mesh>
      <mesh geometry={nodes.Cone003.geometry} position={[2.5, 5, 2]}>
        <meshStandardMaterial color="#a08060" />
      </mesh>
      <mesh
        geometry={nodes.Rosone_Finestra.geometry}
        position={[0, 5.3, -6]}
        rotation={[Math.PI / 2, 0, 0]}
      >
        <meshStandardMaterial color="#c8b89a" />
      </mesh>
      <mesh
        geometry={nodes.Cube008.geometry}
        position={[-2.5, 0.2, 2]}
        scale={[0.5, 0.4, 0.5]}
      >
        <meshStandardMaterial color="#a08060" />
      </mesh>
      <mesh geometry={nodes.Cylinder002.geometry} position={[-2.5, 2.5, 2]}>
        <meshStandardMaterial color="#a08060" />
      </mesh>
      <mesh geometry={nodes.Cone004.geometry} position={[-2.5, 5, 2]}>
        <meshStandardMaterial color="#a08060" />
      </mesh>
      <mesh
        geometry={nodes.Cube009.geometry}
        position={[2.5, 0.2, 2]}
        scale={[0.5, 0.4, 0.5]}
      >
        <meshStandardMaterial color="#a08060" />
      </mesh>
      <mesh geometry={nodes.Cylinder003.geometry} position={[2.5, 2.5, 2]}>
        <meshStandardMaterial color="#a08060" />
      </mesh>
      <mesh
        geometry={nodes.Cone005.geometry}
        position={[0, 3, -6]}
        scale={[2, 1, 1]}
      >
        <meshStandardMaterial color="#a08060" />
      </mesh>
      <mesh
        geometry={nodes.Campanile004.geometry}
        position={[4, 6.753, -3.5]}
        scale={[0.3, 0.1, 0.3]}
      >
        <meshStandardMaterial color="#a08060" />
      </mesh>
      <mesh
        geometry={nodes.Campanile005.geometry}
        position={[-2.328, 6.753, -3.401]}
        scale={[0.3, 0.1, 0.3]}
      >
        <meshStandardMaterial color="#a08060" />
      </mesh>
      <mesh
        geometry={nodes.Campanile006.geometry}
        position={[4.31, 0, -4.399]}
        scale={[0.3, 0.38, 0.3]}
      >
        <meshStandardMaterial color="#c8b89a" />
      </mesh>
      <mesh
        geometry={nodes.Campanile007.geometry}
        position={[3.05, 0, -4.399]}
        scale={[0.3, 0.38, 0.3]}
      >
        <meshStandardMaterial color="#c8b89a" />
      </mesh>
      <mesh
        geometry={nodes.Campanile008.geometry}
        position={[-1.154, 0, -4.399]}
        scale={[0.3, 0.38, 0.3]}
      >
        <meshStandardMaterial color="#c8b89a" />
      </mesh>
      <mesh
        geometry={nodes.Campanile009.geometry}
        position={[-2.294, 0, -4.399]}
        scale={[0.3, 0.38, 0.3]}
      >
        <meshStandardMaterial color="#c8b89a" />
      </mesh>
    </group>
  );
}

useGLTF.preload("/chiesa.glb");

export default Chiesa;
